services:
  - type: web
    name: klassiQ-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: PORT
        value: 10000
    healthCheckPath: /health